titizOto/Areas/radmin/Controllers/CargoController.cs
using HelperAdmin;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using titizOto.Models;

namespace titizOto.Areas.radmin.Controllers
{
    [AccessControl(AccessRole.superAdmin)]
    [BindAdminParameters]
    public class CargoController : DbWithControllerWithSorting<tbl_cargo>
    {
         

    }
}

titizOto/Areas/radmin/Views/Cargo/Create.cshtml
@model tbl_cargo

@{
    ViewBag.Title = @Model.classTitle + " Ekle";
    Layout = "~/Areas/radmin/Views/Shared/_LayoutPageAdmin.cshtml"; 
}

@if (ViewBag.success != null)
{ 
    @Html.Raw(ViewBag.resultHtml)
}


@using (Html.BeginForm("Create", "Cargo", FormMethod.Post, new { @class = "mainForm" }))
{  
    @Html.ValidationSummary(null, new { @class = "validationInfo hideit" }) 
    
    <div class="title">
        <h5>@Model.classTitle Ekleme</h5>
        <a></a>
    </div> 

    <!--Upload-->
    @Html.AntiForgeryToken()

   
    <fieldset>
        <div class="widget">

            <!--Tabs-->
            <ul class="tabs">
                <li><a href="#tab3">Genel İçerik</a></li>
                <li><a href="#tab2">Fotoğraf</a></li>
            </ul>

            <!--Column-->
            <div class="tab_container">
                <div id="tab3" class="tab_content">

                    <!--cargoId -->
                    @Html.HiddenFor(a => a.cargoId, new { @id = "primaryKey" })

                    <!--langId -->
                    <div class="rowElem">@Html.LabelFor(a => a.langId)<div class="formRight">@Html.LangDropDown(a => a.langId)<label class="error">@Html.ValidationMessageFor(a => a.langId)</label></div>
                        <div class="fix"></div>
                    </div>

                    <!--statu -->
                    <div class="rowElem">@Html.LabelFor(a => a.statu)<div class="formRight">@Html.StatuDropDown(a => a.statu)<label class="error">@Html.ValidationMessageFor(a => a.statu)</label></div>
                        <div class="fix"></div>
                    </div>

                    <!--name -->
                    <div class="rowElem">@Html.LabelFor(a => a.name)<div class="formRight">@Html.TextBoxFor(a => a.name)<label class="error">@Html.ValidationMessageFor(a => a.name)</label></div>
                        <div class="fix"></div>
                    </div>

                    <!--price -->
                    <div class="rowElem">@Html.LabelFor(a => a.price)
                        <div class="formRight">@Html.TextBox("price", Model.price.ToString("F2", System.Globalization.CultureInfo.CreateSpecificCulture("en-US")))@Html.TextBoxFor(a => a.price)<label class="error">@Html.ValidationMessageFor(a => a.price)</label></div>
                        <div class="fix"></div>
                    </div>


                    <!--freeCargoPrice -->
                    <div class="rowElem">@Html.LabelFor(a => a.freeCargoPrice)<div class="formRight">@Html.TextBox("freeCargoPrice", Model.freeCargoPrice.ToString("F2", System.Globalization.CultureInfo.CreateSpecificCulture("en-US")))<label class="error">@Html.ValidationMessageFor(a => a.freeCargoPrice)</label></div>
                        <div class="fix"></div>
                    </div>


                    <!--detail -->
                    <div class="rowElem">@Html.LabelFor(a => a.detail)<div class="formRight">@Html.CkeditorHtml(a => a.detail)<label class="error">@Html.ValidationMessageFor(a => a.detail)</label></div>
                        <div class="fix"></div>
                    </div>


                    <!--isCargoPriceOnCustomer -->
                    <div class="rowElem">@Html.LabelFor(a => a.isCargoPriceOnCustomer)<div class="formRight">@Html.StatuDropDown(a => a.isCargoPriceOnCustomer)<label class="error">@Html.ValidationMessageFor(a => a.isCargoPriceOnCustomer)</label></div>
                        <div class="fix"></div>
                    </div>

                     <!--trackUrl -->
  <div class="rowElem">@Html.LabelFor(a => a.trackUrl)<div class="formRight">@Html.TextBoxFor(a => a.trackUrl)<label class="error">@Html.ValidationMessageFor(a => a.trackUrl)</label></div><div class="fix"></div></div>


                    <div class="fix"></div>
                </div>
                 
                <div id="tab2" class="tab_content">

                    <!--photo -->
                    @Html.UploaderWithThumbnailPreview(a => a.photo, "cargo", a => a.photoCoordinate, "150", "150", Url.Content("~/"))<label class="error">@Html.ValidationMessageFor(a => a.photo)</label><div class="fix"></div>

                </div>
            </div>

            <div class="fix"></div>
        </div>
    </fieldset>  
    
    <div class="fix" style="height: 20px"></div>
   
    <!--Buttons-->
    if (ViewBag.success == null || !(bool)ViewBag.success)
    {
    <input type="submit" value="Kaydet" class="redBtn submitForm" />
    }
    <a class="greyishBtn button floatright" href="@Url.Action("Index")">Geri Dön </a>    
    
}

titizOto/Areas/radmin/Views/Cargo/Edit.cshtml
@model tbl_cargo

@{
    ViewBag.Title = @Model.classTitle + " Düzenle";
    Layout = "~/Areas/radmin/Views/Shared/_LayoutPageAdmin.cshtml"; 
}

@if (ViewBag.success != null)
{ 
    @Html.Raw(ViewBag.resultHtml)
}


@using (Html.BeginForm("Edit", "Cargo", FormMethod.Post, new { @class = "mainForm" }))
{  
    @Html.ValidationSummary(null, new { @class = "validationInfo hideit" }) 
    
    <div class="title">
        <h5>@Model.classTitle Düzenle(@Model.name)</h5>
    </div> 

    <!--Upload-->
    @Html.AntiForgeryToken()

   
  <fieldset>
        <div class="widget">

            <!--Tabs-->
            <ul class="tabs">
                <li><a href="#tab3">Genel İçerik</a></li>
                <li><a href="#tab2">Fotoğraf</a></li>
            </ul>

            <!--Column-->
            <div class="tab_container">
                <div id="tab3" class="tab_content">

                    <!--cargoId -->
                    @Html.HiddenFor(a => a.cargoId, new { @id = "primaryKey" })

                    <!--langId -->
                    <div class="rowElem">@Html.LabelFor(a => a.langId)<div class="formRight">@Html.LangDropDown(a => a.langId)<label class="error">@Html.ValidationMessageFor(a => a.langId)</label></div>
                        <div class="fix"></div>
                    </div>

                    <!--statu -->
                    <div class="rowElem">@Html.LabelFor(a => a.statu)<div class="formRight">@Html.StatuDropDown(a => a.statu)<label class="error">@Html.ValidationMessageFor(a => a.statu)</label></div>
                        <div class="fix"></div>
                    </div>

                    <!--name -->
                    <div class="rowElem">@Html.LabelFor(a => a.name)<div class="formRight">@Html.TextBoxFor(a => a.name)<label class="error">@Html.ValidationMessageFor(a => a.name)</label></div>
                        <div class="fix"></div>
                    </div>

                    <!--price -->
                    <div class="rowElem">@Html.LabelFor(a => a.price)
                        <div class="formRight">@Html.TextBox("price", Model.price.ToString("F2", System.Globalization.CultureInfo.CreateSpecificCulture("en-US")))<label class="error">@Html.ValidationMessageFor(a => a.price)</label></div>
                        <div class="fix"></div>
                    </div>


                    <!--freeCargoPrice -->
                    <div class="rowElem">@Html.LabelFor(a => a.freeCargoPrice)<div class="formRight">@Html.TextBox("freeCargoPrice", Model.freeCargoPrice.ToString("F2", System.Globalization.CultureInfo.CreateSpecificCulture("en-US")))<label class="error">@Html.ValidationMessageFor(a => a.freeCargoPrice)</label></div>
                        <div class="fix"></div>
                    </div>


                    <!--detail -->
                    <div class="rowElem">@Html.LabelFor(a => a.detail)<div class="formRight">@Html.CkeditorHtml(a => a.detail)<label class="error">@Html.ValidationMessageFor(a => a.detail)</label></div>
                        <div class="fix"></div>
                    </div>


                    <!--isCargoPriceOnCustomer -->
                    <div class="rowElem">@Html.LabelFor(a => a.isCargoPriceOnCustomer)<div class="formRight">@Html.StatuDropDown(a => a.isCargoPriceOnCustomer)<label class="error">@Html.ValidationMessageFor(a => a.isCargoPriceOnCustomer)</label></div>
                        <div class="fix"></div>
                    </div>

                     <!--trackUrl -->
  <div class="rowElem">@Html.LabelFor(a => a.trackUrl)<div class="formRight">@Html.TextBoxFor(a => a.trackUrl)<label class="error">@Html.ValidationMessageFor(a => a.trackUrl)</label></div><div class="fix"></div></div>


                    <div class="fix"></div>
                </div>
                 
                <div id="tab2" class="tab_content">

                    <!--photo -->
                    @Html.UploaderWithThumbnailPreview(a => a.photo, "cargo", a => a.photoCoordinate, "150", "150", Url.Content("~/"))<label class="error">@Html.ValidationMessageFor(a => a.photo)</label><div class="fix"></div>

                </div>
            </div>

            <div class="fix"></div>
        </div>
    </fieldset>
    
    <div class="fix" style="height: 20px"></div>
   
    <!--Buttons-->
                       
    <input type="submit" value="Kaydet" class="redBtn submitForm" />
                       
    <a class="greyishBtn button floatright" href="@Url.Action("Index")" >Geri Dön </a>    
    
}

titizOto/Areas/radmin/Views/Cargo/GeneralSorting.cshtml
@model List<tbl_cargo>
  

@{
    ViewBag.Title = tbl_cargo.getClassTitle() + " Sıralama";
    Layout = "~/Areas/radmin/Views/Shared/_LayoutPageAdmin.cshtml"; 
}

@if (ViewBag.success != null)
{ 
    @Html.Raw(ViewBag.resultHtml)
}


@using (Html.BeginForm("GeneralSorting", "Slider", FormMethod.Post, new { @class = "mainForm" }))
{  
    @Html.ValidationSummary(null, new { @class = "validationInfo hideit" }) 
    
    <div class="title">
        <h5>@tbl_cargo.getClassTitle() Sıralama</h5>
        <a></a>
    </div> 

    <!--Upload-->
    @Html.AntiForgeryToken()

   
    <fieldset>
        <div class="widget">

            <!--Tabs-->
            <ul class="tabs">
                <li><a href="#tab1">@tbl_cargo.getClassTitle() Sıralama</a></li>

            </ul>

            <!--Column-->
            <div class="tab_container">

                <div id="tab1" class="tab_content">
                     
                     <ul id="sortable">
                            
                              @foreach (var item in Model)
                              {  <li class="ui-state-default" data-id="@item.cargoId"><span class="ui-icon ui-icon-arrowthick-2-n-s"></span>@item.name</li>
                                  
                              }
                        </ul>


                    @Html.Hidden("sortArray")

                </div>


            </div>

            <div class="fix"></div>
        </div>
    </fieldset>  
    
    <div class="fix" style="height: 20px"></div>
   
    <!--Buttons-->
    
    <input type="submit" value="Kaydet" class="redBtn submitForm" />
    
    <a class="greyishBtn button floatright" href="@Url.Action("Index")">Geri Dön </a>    
    
}

titizOto/Areas/radmin/Views/Cargo/Index.cshtml
@model IEnumerable<tbl_cargo>

@{
    Layout = "~/Areas/radmin/Views/Shared/_LayoutPageAdmin.cshtml";
    ViewBag.Title = tbl_cargo.getClassTitle() + " Yönetimi";
}

<div class="title">
    <h5>@tbl_cargo.getClassTitle() Yönetimi</h5>
</div>

<div class="body alignLeft">
    <div class="proccess floatright">
        <select>
            <option value="-1">İşlem Seçiniz</option>
            <option>Sil</option>
            <option>Sırala</option>
            <option>Aktif</option>
            <option>Pasif</option>
        </select>
    </div>
    <a href="@Url.Action("create")" title="" class="btnIconLeft mr10 mt5">
        <img src="@Url.Content("~/Areas/radmin/Content/images/icons/dark/add.png")" alt="" class="icon" /><span>Yeni @tbl_cargo.getClassTitle() Ekle</span></a>
  <a href="@Url.Action("GeneralSorting")" title="" class="btnIconLeft mr10 mt5">
        <img src="@Url.Content("~/Areas/radmin/Content/images/icons/dark/podium.png")" alt="" class="icon" /><span>Genel @tbl_cargo.getClassTitle() Sıralama</span></a>
    <div class="fix"></div>
</div>

<div class="table">
    @Html.Partial("Table", Model)
</div>

titizOto/Areas/radmin/Views/Cargo/Table.cshtml
@model IEnumerable<tbl_cargo>

<div class="head">
</div>
<form>

    @Html.Hidden("controlName", ViewContext.RouteData.Values["Controller"])

    <table id="indexTable" border="0" cellpadding="0" cellspacing="0" class="display"> 
        <thead>
            <tr>
                <th class="nosortable"></th>
                <th>#</th> 
                   <th>
                    @Html.DisplayNameFor(model => model.name)
                </th> 
                <th>
                   Fotoğraf
                </th> 
                <th style="width: 50px">
                    @Html.DisplayNameFor(model => model.sequence)
                </th> 
                <th>
                    @Html.DisplayNameFor(model => model.statu)
                </th>
                <th>İşlem</th>
            </tr>
        </thead>

        <tbody>
            @{ int index = 1;
            }

            @foreach (var item in Model)
            {
                <tr class="gradeA">
                    <td class="center">
                        @Html.CheckBox("selectedItem", new { value = item.cargoId })
                    </td>
                    <td class="center">@index</td>
                    <td class="center">@item.name</td>
                    <td class="center">
                         <a href="@Url.Content("~/Download/item/cargo/"+item.photo)" data-lightbox="@item.photo" ><img src="@Url.Content("~/Download/item/cargo/"+item.photo)" width="100" /></a>
                    </td>
                    <td class="center">
                        @Html.TextBox("seq" + item.cargoId, item.sequence, new { @class = "seqBox onlyNums" })
                    </td>
                    <td class="center">
                        @Html.getStatus(modelItem => item.statu)
                    </td>
                    <td class="center editBtn" data-id="@item.cargoId">
                        <a title="Düzenle" class="btn14 mr5" href="@Url.Action("Edit", new { id = item.cargoId })">
                            <img  src="@Url.Content("~/Areas/radmin/Content/images/icons/dark/pencil.png")"/></a>
                        <a class="btn14 mr5 ajx" data-action="moveUp" title="Yukarı Taşı">
                            <img  src="@Url.Content("~/Areas/radmin/Content/images/icons/dark/arrowUp.png")"/></a>
                        <a class="btn14 mr5 ajx" data-action="moveDown" title="Aşağı Taşı">
                            <img  src="@Url.Content("~/Areas/radmin/Content/images/icons/dark/arrowDown.png")"/></a>
                        <a class="btn14 mr5 delete ajx" data-action="delete" title="Sil">
                            <img  src="@Url.Content("~/Areas/radmin/Content/images/icons/dark/trash.png")"/></a>
                    </td>
                </tr>
                
                index = index + 1;
            }

        </tbody>
    </table>
</form>