titizOto/Areas/radmin/Controllers/PosOptionController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using HelperAdmin;
using titizOto.Models;

namespace titizOto.Areas.radmin.Controllers
{
    [AccessControl(AccessRole.superAdmin)]
    [BindAdminParameters]
    public class PosOptionController : DbWithControllerWithSortingWithFilter<tbl_bankPosOption>
    {
        public override List<tbl_bankPosOption> getListWithFilter(int filterId)
        {
            return base.getListWithFilter(filterId).Where(a => a.bankPosId == filterId).OrderBy(a => a.paymentCount).ToList();
        }

    }
}

titizOto/Areas/radmin/Views/PosOption/Create.cshtml
@model tbl_bankPosOption

@{
    ViewBag.Title = Model.classTitle + " Ekle";
    Layout = "~/Areas/radmin/Views/Shared/_LayoutPageAdmin.cshtml";

    int bankPosId = 0; 
}

@if (ViewBag.success != null)
{ 
    @Html.Raw(ViewBag.resultHtml)
}

@if (ViewContext.RouteData.Values["filterId"] != null)
{
    bankPosId = int.Parse(ViewContext.RouteData.Values["filterId"].ToString());
}

@using (Html.BeginForm("Create", "PosOption", FormMethod.Post, new { @class = "mainForm" }))
{  
    @Html.ValidationSummary(null, new { @class = "validationInfo hideit" }) 
    
    <div class="title">
        <h5>@Model.classTitle Ekleme</h5>
        <a></a>
    </div> 

    <!--Upload-->
    @Html.AntiForgeryToken()

   
    <fieldset>
        <div class="widget">

            <!--Tabs-->
            <ul class="tabs">
                <li><a href="#tab1">Genel</a></li>

            </ul>

            <!--Column-->
            <div class="tab_container">

                <div id="tab1" class="tab_content"> 

                    <!--bankPosOptionId -->
                    @Html.HiddenFor(a => a.bankPosOptionId, new { @id = "primaryKey" })

                    @Html.Hidden("bankPosId", bankPosId) 

                    <!--paymentCount -->
                    <div class="rowElem">@Html.LabelFor(a => a.paymentCount)<div class="formRight">@Html.TextBoxFor(a => a.paymentCount)<label
                        class="error">@Html.ValidationMessageFor(a => a.paymentCount)</label></div>
                        <div class="fix"></div>
                    </div>

                    <!--minBasketAmount -->
                    <div class="rowElem">@Html.LabelFor(a => a.minBasketAmount)<div class="formRight">@Html.TextBox("minBasketAmount",Model.minBasketAmount.ToString("F2", System.Globalization.CultureInfo.CreateSpecificCulture("en-US")))<label
                        class="error">@Html.ValidationMessageFor(a => a.minBasketAmount)</label></div>
                        <div class="fix"></div>
                    </div>

                    <!--additionalAmount -->
                    <div class="rowElem">@Html.LabelFor(a => a.additionalAmount)<div class="formRight">@Html.TextBox("additionalAmount",Model.additionalAmount.ToString("F2", System.Globalization.CultureInfo.CreateSpecificCulture("en-US")))<label
                        class="error">@Html.ValidationMessageFor(a => a.additionalAmount)</label></div>
                        <div class="fix"></div>
                    </div>

                    <!--statu -->
                    <div class="rowElem">@Html.LabelFor(a => a.statu)<div class="formRight">@Html.StatuDropDown(a => a.statu)<label
                        class="error">@Html.ValidationMessageFor(a => a.statu)</label></div>
                        <div class="fix"></div>
                    </div> 
                </div>


            </div>

            <div class="fix"></div>
        </div>
    </fieldset>  
    
    <div class="fix" style="height: 20px"></div>
   
    <!--Buttons-->
    if (ViewBag.success == null || !(bool)ViewBag.success)
    {
    <input type="submit" value="Kaydet" class="redBtn submitForm" />
    }
    <a class="greyishBtn button floatright" href="@Url.Action("IndexWithFilter", new { filterId = bankPosId.ToString() })" >
        Geri Dön </a>    
    
}

titizOto/Areas/radmin/Views/PosOption/Edit.cshtml
@model tbl_bankPosOption

@{
    ViewBag.Title = Model.classTitle + " Düzenle";
    Layout = "~/Areas/radmin/Views/Shared/_LayoutPageAdmin.cshtml";

    int bankPosId = 0; 
}

@if (ViewBag.success != null)
{ 
    @Html.Raw(ViewBag.resultHtml)
}

@if (ViewContext.RouteData.Values["filterId"] != null)
{
    bankPosId = int.Parse(ViewContext.RouteData.Values["filterId"].ToString());
}

@using (Html.BeginForm("Edit", "PosOption", FormMethod.Post, new { @class = "mainForm" }))
{  
    @Html.ValidationSummary(null, new { @class = "validationInfo hideit" }) 
    
    <div class="title">
        <h5>@Model.classTitle Düzenle(@Model.paymentCount)</h5>
        <a></a>
    </div> 

    <!--Upload-->
    @Html.AntiForgeryToken()

   
    <fieldset>
        <div class="widget">

            <!--Tabs-->
            <ul class="tabs">
                <li><a href="#tab1">Genel</a></li>

            </ul>

            <!--Column-->
            <div class="tab_container">

                <div id="tab1" class="tab_content">

                    <!--bankPosOptionId -->
                    @Html.HiddenFor(a => a.bankPosOptionId, new { @id = "primaryKey" })

                    @Html.Hidden("bankPosId", bankPosId)

                    <!--paymentCount -->
                    <div class="rowElem">@Html.LabelFor(a => a.paymentCount)<div class="formRight">@Html.TextBoxFor(a => a.paymentCount)<label
                        class="error">@Html.ValidationMessageFor(a => a.paymentCount)</label>
                        </div>
                        <div class="fix"></div>
                    </div>

                    <!--minBasketAmount -->
                    <div class="rowElem">@Html.LabelFor(a => a.minBasketAmount)<div class="formRight">@Html.TextBox("minBasketAmount", Model.minBasketAmount.ToString("F2", System.Globalization.CultureInfo.CreateSpecificCulture("en-US")))<label
                        class="error">@Html.ValidationMessageFor(a => a.minBasketAmount)</label>
                        </div>
                        <div class="fix"></div>
                    </div>

                    <!--additionalAmount -->
                    <div class="rowElem">@Html.LabelFor(a => a.additionalAmount)<div class="formRight">@Html.TextBox("additionalAmount", Model.additionalAmount.ToString("F2", System.Globalization.CultureInfo.CreateSpecificCulture("en-US")))<label
                        class="error">@Html.ValidationMessageFor(a => a.additionalAmount)</label>
                        </div>
                        <div class="fix"></div>
                    </div>

                    <!--statu -->
                    <div class="rowElem">@Html.LabelFor(a => a.statu)<div class="formRight">@Html.StatuDropDown(a => a.statu)<label
                        class="error">@Html.ValidationMessageFor(a => a.statu)</label>
                        </div>
                        <div class="fix"></div>
                    </div>

                </div>


            </div>

            <div class="fix"></div>
        </div>
    </fieldset>
    
    <div class="fix" style="height: 20px"></div>
   
    <!--Buttons-->
                       
    <input type="submit" value="Kaydet" class="redBtn submitForm" />
                      
    <a class="greyishBtn button floatright" href="@Url.Action("IndexWithFilter", new { filterId = bankPosId.ToString() })" >
        Geri Dön </a>    
    
}

titizOto/Areas/radmin/Views/PosOption/IndexWithFilter.cshtml
@model IEnumerable<tbl_bankPosOption>

@{
    Layout = "~/Areas/radmin/Views/Shared/_LayoutPageAdmin.cshtml";
    ViewBag.Title = tbl_bankPosOption.getClassTitle() + " Yönetimi";
}

<div class="title">
    <h5>@tbl_bankPosOption.getClassTitle() Yönetimi</h5>
</div>

<div class="body alignLeft">
    <div class="proccess floatright">
        <select>
            <option value="-1">İşlem Seçiniz</option>
            <option>Sil</option> 
        </select>
    </div>

    @*-------------&&& Create &&&-------------  *@
    <a href="@Url.Action("create", new { filterId = ViewContext.RouteData.Values["filterId"].ToString() })" title="" class="btnIconLeft mr10 mt5">
        <img src="@Url.Content("~/Areas/radmin/Content/images/icons/dark/add.png")" alt="" class="icon" /><span>Yeni
            @tbl_bankPosOption.getClassTitle() Ekle</span></a>
             

    @*-------------&&& Back &&&-------------  *@
    <a href="@Url.Action("Index", new { controller = "Pos" })" title="" class="btnIconLeft mr10 mt5">
        <img src="@Url.Content("~/Areas/radmin/Content/images/icons/dark/arrowLeft.png")" alt="" class="icon" /><span>Pos Yönetimine
            Geri Dön</span></a>
</div>

<div class="table">
    @Html.Partial("Table", Model)
</div>

titizOto/Areas/radmin/Views/PosOption/Table.cshtml
@model IEnumerable<tbl_bankPosOption>

<div class="head">
</div>
<form>

    @Html.Hidden("controlName", ViewContext.RouteData.Values["Controller"])
    @Html.Hidden("filterId", ViewContext.RouteData.Values["filterId"])

    <table id="indexTable" border="0" cellpadding="0" cellspacing="0" class="display">

        <thead>
            <tr>
                <th class="nosortable"></th>

                <th>@Html.DisplayNameFor(model => model.paymentCount)
                </th>

                <th>
                    @Html.DisplayNameFor(model => model.statu)
                </th>
                <th>İşlem</th>
            </tr>
        </thead>

        <tbody>
            @{ int index = 1;
            }

            @foreach (var item in Model)
            {
                <tr class="gradeA">
                    <td class="center">
                        @Html.CheckBox("selectedItem", new { value = item.bankPosOptionId })
                    </td>

                    <td class="center">@item.paymentCount</td>

                    <td class="center">
                        @Html.getStatus(modelItem => item.statu)
                    </td>


                    <td class="center editBtn" data-id="@item.bankPosOptionId">

                        <a title="Düzenle" class="btn14 mr5" href="@Url.Action("Edit", new { id = item.bankPosOptionId, filterId = item.bankPosId })">
                            <img  src="@Url.Content("~/Areas/radmin/Content/images/icons/dark/pencil.png")"/></a>
                        <a class="btn14 mr5 delete ajx" data-action="deleteWithFilter" title="Sil">
                            <img  src="@Url.Content("~/Areas/radmin/Content/images/icons/dark/trash.png")"/></a>
                    </td>
                </tr>
                
                index = index + 1;
            }

        </tbody>
    </table>
</form>